# CAMB parameter file for LCDM baseline
# Planck 2018 TTTEEE+lowE+lens+BAO best-fit
# Sameer Khan, 2026

# Cosmological parameters
ombh2 = 0.02237
omch2 = 0.1200
omnuh2 = 0.00064
omk = 0
hubble = 67.36
tau = 0.0544
As = 2.100e-9
ns = 0.9649
pivot_scalar = 0.05
pivot_tensor = 0.05

# Recombination
recombination_model = RECFAST
RECFAST_fudge = 1.14

# Output
get_scalar_cls = T
get_vector_cls = F
get_tensor_cls = F
get_transfer = F
l_max_scalar = 4000
k_eta_max_scalar = 8000

# Accuracy
accuracy_boost = 1
l_accuracy_boost = 1
l_sample_boost = 1
high_l_unlensed_cl_template = T

# We only need TT,TE,EE
do_lensing = T
lens_potential_output_file = not_needed
